import type { RoleCard } from "@/lib/game/types";

export const roles: RoleCard[] = [
  {
    id: "notaire",
    name: "Notaire",
    category: "pression",
    timing: "enquete",
    effect: "Force une reponse officielle en oui, non ou je ne sais pas.",
    limitation: "Une fois par partie.",
    masterInstruction: "Note la question et demande une reponse officielle courte.",
    playerHint: "Utilise-le pour verrouiller une piste avant le Conseil.",
    image: "/assets/cards/roles/notaire.webp",
  },
  {
    id: "archiviste",
    name: "Archiviste",
    category: "information",
    timing: "pouvoirs",
    effect: "Recoit en prive un vrai element d'une affaire non revelee qui n'est pas la sienne.",
    limitation: "Une fois par partie.",
    masterInstruction: "Choisis un element vrai et lis-le discretement au joueur.",
    playerHint: "Garde l'indice pour tester deux personnes sans tout devoiler.",
    image: "/assets/cards/roles/archiviste.webp",
  },
  {
    id: "garde-champetre",
    name: "Garde champetre",
    category: "protection",
    timing: "defense",
    effect: "Annule une accusation correcte visant son equipe.",
    limitation: "Une fois par partie, seulement si son secret n'est pas revele.",
    masterInstruction: "Passe le verdict en bloque et consomme le pouvoir.",
    playerHint: "C'est ton filet de securite, pas une preuve d'innocence.",
    image: "/assets/cards/roles/garde-champetre.webp",
  },
  {
    id: "faussaire",
    name: "Faussaire",
    category: "desordre",
    timing: "enquete",
    effect: "Declare une reponse officielle comme potentiellement fausse.",
    limitation: "Une fois par partie.",
    masterInstruction: "Marque la reponse comme troublee dans l'historique oral.",
    playerHint: "Ideal pour brouiller une accusation qui arrive trop vite.",
    image: "/assets/cards/roles/faussaire.webp",
  },
  {
    id: "maire",
    name: "Maire",
    category: "pression",
    timing: "enquete",
    effect: "Declenche immediatement un mini-conseil d'une seule accusation.",
    limitation: "Une fois par partie.",
    masterInstruction: "Interromps la phase et ouvre une accusation publique.",
    playerHint: "Utilise-le quand tout le monde tourne autour d'un secret.",
    image: "/assets/cards/roles/maire.webp",
  },
  {
    id: "serrurier",
    name: "Serrurier",
    category: "information",
    timing: "pouvoirs",
    effect: "Demande si deux elements peuvent appartenir a la meme affaire.",
    limitation: "Une fois par partie.",
    masterInstruction: "Reponds seulement compatible ou incompatible.",
    playerHint: "Parfait pour verifier une cle, un lieu ou un objet suspect.",
    image: "/assets/cards/roles/serrurier.webp",
  },
  {
    id: "commere",
    name: "Commere",
    category: "information",
    timing: "enquete",
    effect: "Consulte en prive la derniere reponse officielle donnee par un joueur.",
    limitation: "Une fois par partie.",
    masterInstruction: "Repete discretement la derniere reponse officielle.",
    playerHint: "Tu peux recouper une contradiction sans l'annoncer.",
    image: "/assets/cards/roles/commere.webp",
  },
  {
    id: "guerisseuse",
    name: "Guerisseuse",
    category: "protection",
    timing: "resolution",
    effect: "Retire un soupcon a un joueur.",
    limitation: "Une fois par partie.",
    masterInstruction: "Retire un soupcon public au joueur choisi.",
    playerHint: "Sauve un allie, ou achete une confiance fragile.",
    image: "/assets/cards/roles/guerisseuse.webp",
  },
  {
    id: "cartographe",
    name: "Cartographe",
    category: "information",
    timing: "pouvoirs",
    effect: "Apprend un lieu d'une affaire non revelee qui n'est pas la sienne.",
    limitation: "Une fois par partie.",
    masterInstruction: "Donne un lieu vrai hors de son propre secret.",
    playerHint: "Un lieu suffit parfois a reperer le bon duo.",
    image: "/assets/cards/roles/cartographe.webp",
  },
  {
    id: "horloger",
    name: "Horloger",
    category: "tempo",
    timing: "enquete",
    effect: "Ajoute ou retire 90 secondes a la phase en cours.",
    limitation: "Une fois par partie.",
    masterInstruction: "Ajuste le timer et annonce le changement.",
    playerHint: "Raccourcis une piste dangereuse ou prolonge une embuscade.",
    image: "/assets/cards/roles/horloger.webp",
  },
  {
    id: "messager",
    name: "Messager",
    category: "desordre",
    timing: "pouvoirs",
    effect: "Fait passer une question privee via le narrateur.",
    limitation: "Une fois par partie.",
    masterInstruction: "Lis la question au joueur cible et rapporte la reponse.",
    playerHint: "Pose une question que tu ne veux pas assumer en public.",
    image: "/assets/cards/roles/messager.webp",
  },
  {
    id: "crieur-public",
    name: "Crieur public",
    category: "pression",
    timing: "enquete",
    effect: "Force un joueur a repeter publiquement une reponse recente.",
    limitation: "Une fois par partie.",
    masterInstruction: "Demande au joueur de repeter mot pour mot la reponse.",
    playerHint: "Tres fort contre les demi-aveux marmonnes.",
    image: "/assets/cards/roles/crieur-public.webp",
  },
];

export function getRole(roleId: string): RoleCard {
  const role = roles.find((item) => item.id === roleId);

  if (!role) {
    throw new Error(`Unknown role: ${roleId}`);
  }

  return role;
}
